### ISSUE TITLE
Hover over a function show always "Loading..." and never stop

### ISSUE THREAD

**Issue by varosi** [haskelly-dev/Haskelly#47] opened 2017-05-25 11:53 UTC
I'm using latest versions of VS Code, Intero, Haskelly on Windows 10.

When I hoved over a function I always see "Loading..." in the hint.
There are no errors seen.

**Comment by martrik** [comment] 2017-05-26 11:45
Hi Varosi! What's the path to the file that you are trying to get hover information from? Does code completion work by the way?

**Comment by varosi** [comment] 2017-05-30 16:53
Path is: **D:\Projects\teo\app\Main.hs**
Code completion is giving the same message "Loading..." and nothing happens.

**Comment by varosi** [comment] 2017-05-30 16:56
I saw this error in Developer Tools | Console:
```
[Extension Host] Trying new Intero from document D:\Projects\teo\app\Main.hs
extensionHost.ts:285 [Extension Host] Uncaught Exception:  Error: spawn stack ENOENT
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] Error: spawn stack ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:285 [Extension Host] Intero failed to load
extensionHost.ts:285 [Extension Host] Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at SyncSpawn.runSyncCommand (C:\Users\varosi\.vscode\extensions\UCL.haskelly-0.4.21\out\src\Providers\InitIntero.js:68:26)
    at new SyncSpawn (C:\Users\varosi\.vscode\extensions\UCL.haskelly-0.4.21\out\src\Providers\InitIntero.js:9:14)
    at Promise (C:\Users\varosi\.vscode\extensions\UCL.haskelly-0.4.21\out\src\Providers\InteroSpawn.js:47:32)
d.logExtensionHostMessage @ extensionHost.ts:285
(anonymous) @ extensionHost.ts:139
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
shell.ts:474 spawn stack ENOENT: Error: spawn stack ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by nameoverflow** [comment] 2017-06-12 11:35
+1
Intero works well in command line REPL, Code completion doesn't show at all. Same error massage.

**Comment by martrik** [comment] 2017-06-16 10:39
Thanks for the bug report. We'll look into it!

**Comment by johannesegger** [comment] 2017-07-25 19:59
I had the same problem. Digging into it I found that the problem was running `stack query file.js` which gave me

> Compiler version mismatched, found ghc-8.0.1 (x86_64), but expected minor version match with ghc-8.0.2 (x86_64) ...

I'm currently upgrading GHC and I'm confident that Haskelly will start working again.

**Comment by varosi** [comment] 2017-07-26 20:47
My problem was that I had two plug-ins for Haskell installed - Haskelly and Haskero. When I deinstalled Haskero everything run fine. But it'll be good if there is some kind of warning message about that.

**Comment by vilinski** [comment] 2017-07-27 20:53
Pretty cool extension. But I'm also observing "Loading..." on hover on MacOS. The console messages, excluding all that snippet syntax warnings, are:

> [Extension Host] Trying new Intero from document /Users/me/Projects/haskell/yesod-mongo/src/Handler/Profile.hs
extensionHost.ts:320 [Extension Host] Intero failed to load
extensionHost.ts:320 [Extension Host] undefined

already removed the `~/.stack` and `project/.stack-work` folders and made `stack install intero` again. but this doesn't help. how to check intero whether it runs in console or repl?
I also had Haskero, but uninstalled it also. Any other suggestions what could help?

**Comment by kemsky** [comment] 2017-08-10 20:18
`cwd` parameter is incorrect on windows `Object {cwd: "/Dev/Projects/haskell-hello/"}`

**Comment by martrik** [comment] 2017-08-12 08:02
Hi @kemsky, thanks for getting in touch. What do you think should be the `cwd` param?

**Comment by kemsky** [comment] 2017-08-12 19:15
I have changed it manually to `D:/Dev/Projects/haskell-hello/` (because it is actual project path, windows) and it worked.

**Comment by vanashimko** [comment] 2017-08-18 13:16
Confirm. Solved the problem by commenting out [this line](https://github.com/haskelly-dev/Haskelly/blob/deb82c91c4b8e0c124990c3ffecffe118eb9a50c/src/utils/workDir.ts#L13). Could you please explain the purpose of removing first two characters on Windows (the drive letter)?

**Comment by martrik** [comment] 2017-08-27 08:24
@vanashimko so even after commenting the line is still does not work? We've released a new version (0.4.24) with that line commented out. Could you let us know what kind of error do you experience (if you could open the Dev Tools and take a screenshot of the console that would be even more useful). Thanks!

**Comment by fly** [comment] 2017-09-05 14:40
@martrik, this is still a problem for me. VSCode 1.15.1, Haskelly 0.4.24.
This is what I see: https://imgur.com/Hzqd9cs

**Comment by fly** [comment] 2017-09-05 14:47
And when I switched to terminal tab, I got another error. With exception now: https://imgur.com/HGNlz5I

**Comment by martrik** [comment] 2017-09-09 10:28
Hi @fly! I'll need a bit of your help here. We've published a new version (0.4.25) with a more detailed log so that we can see what might be going wrong. Could you just retry the situation of the previous two screenshots with this new version. Also, just to confirm, does the command `stack ghci --with-ghc intero` work correctly in your default terminal?

**Comment by fly** [comment] 2017-09-09 10:34
@martrik I'm unable to reproduce it anymore. There is another problem with spaces in path, but that's [another](https://github.com/haskelly-dev/Haskelly/pull/54) story. With changes mentioned in that PR, everything seems to be fine for me.

**Comment by martrik** [comment] 2017-09-09 10:49
We've released a new version that includes the PR from @fly (#54). As mentioned in the PR, once this other [PR](https://github.com/commercialhaskell/intero/issues/381#issuecomment-328259049) from the Intero's repo is merged, this problem should be solved. We'll close this issue once that happens.

**Comment by martrik** [comment] 2017-11-05 11:41
The PR has been merged now and so the problem should be solved. Therefore, we're closing this issue.

**Closed by martrik** 2017-11-05 11:41 UTC
Labels: bug
